name: Hello world
author: Nurbol
description: A simple "Hello world" GitHub Action
inputs:
  who-to-greet:
    description: "Who to greet"
    default: "Bobik"
outputs:
  time:
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
  env:
    HELLO: WORLD
  post-entrypoint: cleanup.sh
