name: Hello world
author: Nurbol
description: A simple "Hello world" GitHub Action
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time:
    description: "The time we greeted you"
runs:
  using: "node24"
  main: index.js
  pre: setup.js
  pre-if: runner.os == 'linux'
  post: cleanup.js
  post-if: runner.os == 'linux'
